#!/bin/bash
SCRIPT_DIR="$(dirname "$0")"
cd $SCRIPT_DIR
echo $SCRIPT_DIR

for NODE in broker coordinator historical overlord realtime
do
    nohup ./${NODE}_start >> $ROOT/logs/kloepper_scrath2/${NODE}.log &
done
