#!/bin/bash
SCRIPT_DIR="$(dirname "$0")"
cd $SCRIPT_DIR
echo $SCRIPT_DIR

./stop_all

for NODE in broker coordinator historical overlord
do
    nohup ./${NODE}_start >> $ROOT/logs/$YINST_PKGNAME/${NODE}.log &
done
